CREATE TABLE "dim_date" (
  "date_key" int PRIMARY KEY,
  "date_actual" date NOT NULL,
  "day_of_week" smallint NOT NULL,
  "week_of_year" smallint NOT NULL,
  "month" smallint NOT NULL,
  "month_name" varchar NOT NULL,
  "quarter" smallint NOT NULL,
  "year" int NOT NULL,
  "is_weekend" boolean NOT NULL
);

CREATE TABLE "dim_region" (
  "region_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "region_id_bk" int UNIQUE,
  "region_name" varchar NOT NULL,
  "country_name" varchar NOT NULL
);

CREATE TABLE "dim_customer" (
  "customer_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id_bk" int UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "registration_date" date
);

CREATE TABLE "dim_category" (
  "category_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id_bk" int UNIQUE NOT NULL,
  "category_name" varchar NOT NULL,
  "parent_category_bk" int,
  "level_num" smallint,
  "path_text" text
);

CREATE TABLE "dim_product" (
  "product_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id_bk" int UNIQUE NOT NULL,
  "product_name" varchar NOT NULL,
  "price_current" decimal(18,2),
  "category_key" int NOT NULL
);

CREATE TABLE "dim_payment_method" (
  "payment_method_key" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_code" varchar UNIQUE NOT NULL
);

CREATE TABLE "fact_sales" (
  "fact_sales_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_date_key" int NOT NULL,
  "customer_key" int NOT NULL,
  "product_key" int NOT NULL,
  "region_key" int NOT NULL,
  "order_id_bk" int NOT NULL,
  "order_item_id_bk" int UNIQUE NOT NULL,
  "quantity" decimal(18,3) NOT NULL,
  "unit_price" decimal(18,2) NOT NULL,
  "line_amount" decimal(18,2)
);

CREATE TABLE "fact_transactions" (
  "fact_txn_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "txn_date_key" int NOT NULL,
  "customer_key" int NOT NULL,
  "region_key" int NOT NULL,
  "payment_method_key" int NOT NULL,
  "order_id_bk" int NOT NULL,
  "transaction_id_bk" int UNIQUE NOT NULL,
  "amount" decimal(18,2) NOT NULL
);

COMMENT ON COLUMN "fact_sales"."line_amount" IS 'derived = quantity*unit_price';

ALTER TABLE "dim_product" ADD FOREIGN KEY ("category_key") REFERENCES "dim_category" ("category_key");

ALTER TABLE "fact_sales" ADD FOREIGN KEY ("order_date_key") REFERENCES "dim_date" ("date_key");

ALTER TABLE "fact_sales" ADD FOREIGN KEY ("customer_key") REFERENCES "dim_customer" ("customer_key");

ALTER TABLE "fact_sales" ADD FOREIGN KEY ("product_key") REFERENCES "dim_product" ("product_key");

ALTER TABLE "fact_sales" ADD FOREIGN KEY ("region_key") REFERENCES "dim_region" ("region_key");

ALTER TABLE "fact_transactions" ADD FOREIGN KEY ("txn_date_key") REFERENCES "dim_date" ("date_key");

ALTER TABLE "fact_transactions" ADD FOREIGN KEY ("customer_key") REFERENCES "dim_customer" ("customer_key");

ALTER TABLE "fact_transactions" ADD FOREIGN KEY ("region_key") REFERENCES "dim_region" ("region_key");

ALTER TABLE "fact_transactions" ADD FOREIGN KEY ("payment_method_key") REFERENCES "dim_payment_method" ("payment_method_key");
